///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesTaskmanager(Background) = 'assets/images/app_background.svg';
  static const String imagesTaskmanager(logo)svg = 'assets/images/app_logo.svg';

}
